### ISSUE TITLE
LoginPickVIEW:

### ISSUE THREAD

**Issue by AdaptiveStep** [chrisjcm/G2SystemsWPF#11]
- [x] Basic view är färdig
- [x] Fungerar att logga in på rätt view (fungerar med dapper och databas)
- [x] Visar nästa view korrekt
- [ ] Visar begränsat antal grejer beroende på vem som loggar in
- [x] Är MVVM
- [x] Är ReactUI
- [x] Har alla models och Viewmodels färdiga
- [x] Följer färgpaletten
- [x] Material design
### extra krav
- [ ] Är fix storlek

**Comment by andretheprogrammer** [comment]
Tror ej jag lyckas lösa detta i tid (  Visar begränsat antal grejer beroende på vem som loggar in )
